## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - 1.4
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false